숏 폼 비디오 스트리밍
boostcampwm2023/and03_movemove pull request #20
Opened 2023-11-15 07:41 UTC by junjange

resolved: #8

# 작업 내용
- 숏 폼 UI
- 비디오 스트리밍
- 비디오 스트리밍 상하 스크롤

# 전달 사항
- 데이터 값은 임시적으로 정의하여 구현했습니다.
- data class 구현시 수정하도록 하겠습니다.
- 숏 폼 상하로 스크롤시 비디오가 살짝 느리게 실행될 경우, 하단 컨텐츠의 색상과 비디오 백그라운드 색상이 분리되어 보이는 현상이 발생합니다.
- 비디오 스트리밍에 대해 학습하여 개선해나가겠습니다.

2023-11-15 09:26 UTC, jangjh123 requested changes

2023-11-15 09:26 UTC, jangjh123 commented on client/presentation/build.gradle.kts
> +    implementation(libs.media3.ui)
`VersionCatalog` 의 `[bundle]` 탭에 번들로 묶어 적용하는 편이 좋아 보입니다!

2023-11-15 09:26 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
> +val grey300 = Color(0xFFE0E0E0)
캐피탈로 시작하는 컨벤션 지켜주시고, `grey300` 이라는 명칭 또한 의미를 잘 모르겠습니다. 더 나은 네이밍은 없을까요?

2023-11-15 09:26 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Type.kt
> +    ),
👍

2023-11-15 09:40 UTC, upsk1 submitted a review, later dismissed
고생하셨어요 👍

2023-11-15 10:30 UTC, junjange commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/theme/Color.kt
> +val grey300 = Color(0xFFE0E0E0)
의도는 https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors 머티리얼 디자인 네이밍을 활용하려고 한 거였습니다!! 한번 더 네이밍을 고민해 봐야겠습니다!!

2023-11-15 12:15 UTC, jangjh123 requested changes

2023-11-15 12:15 UTC, jangjh123 commented on client/gradle/libs.versions.toml
> +media3 = ["media3-common", "media3-exoplayer", "media3-ui"]
👍

2023-11-15 12:15 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +            color = VideoDescriptionInDark,
추후 라이트 모드 적용을 용이하게 하기 위해 
```
color = MaterialTheme.colorScheme.~
```
로 수정이 필요해 보입니다!

2023-11-15 12:15 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +    }
이렇게 작성하면 모든 페이지마다 하나 씩 `ExoPlayer` 가 생기게 되는 걸까요?
만약 그렇다면, 각 `ExoPlayer` 객체는 `Recomposition` 에 대해 안전한가요? 사이드 이펙트에 대한 추가적인 고려가 필요해 보입니다. 아시는 바가 있으시면 코멘트 부탁드려요!

2023-11-15 12:21 UTC, jangjh123 requested changes

2023-11-15 12:21 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +    }
이렇게 작성하면 모든 페이지마다 하나 씩 `ExoPlayer` 가 생기게 되는 걸까요?
만약 그렇다면, 각 `ExoPlayer` 객체는 `Recomposition` 에 대해 안전한가요? 사이드 이펙트에 대한 추가적인 고려가 필요해 보입니다. 아시는 바가 있으시면 코멘트 부탁드려요!

2023-11-15 12:43 UTC, junjange commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +            .padding(top = 30.dp, start = 16.dp, bottom = 18.dp),
네네!!

2023-11-15 12:43 UTC, junjange commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +                    )
좋습니다!!

2023-11-15 12:44 UTC, junjange commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/main/watching_video/WatchingVideoScreen.kt
> +            color = VideoDescriptionInDark,
네네!!

2023-11-16 01:04 UTC, jangjh123 submitted a review, later dismissed

2023-11-16 01:12 UTC, jangjh123 reviewed
페이저와 `ExoPlayer` 에 발생할 수 있는 문제가 없다고 판단되면 머지하셔도 좋아요!

2023-11-16 04:11 UTC, jangjh123 approved these changes
LGTM! 감사합니다!

2023-11-16 04:11 UTC, merged