카카오, 구글 로그인 구현
boostcampwm2023/and03_movemove pull request #47
Opened 2023-11-20 07:34 UTC by upsk1

resolved: [#12]

# 작업 내용
- 카카오 로그인 구현
- 구글 로그인 구현

# 전달 사항
커밋명과 브랜치명이 이상합니다 (__) 다음부터 더 주의하겠습니다

2023-11-20 08:29 UTC, jangjh123 requested changes

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/build.gradle.kts
> +    implementation ("com.google.android.gms:play-services-auth:20.5.0")
`VersionCatalog` 로 대체해주시면 되겠습니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +    val signInRequestCode = 1
이런 일반적인 상수값은 `companion object` 로 처리하는 것이 가독성 측면에서 좋아 보입니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +            Log.d("에러상황", "발생2")
로그 지워주세요!

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +            Log.d("에러상황", "발생2")
추가로, `catch` 에 대한 별도의 예외 처리도 필요해 보입니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                        text = "카카오 로그인",
텍스트 하드 코딩은 지양해 주세요ㅎㅎ

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                        painter = painterResource(id = drawable.ic_kakao_login), contentDescription = "null", modifier = Modifier.align(alignment = Alignment.CenterStart)
컨벤션 지켜주시면 좋을 것 같습니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                    containerColor = KakaoYellow, contentColor = Color.Black
컨벤션 지켜주시면 좋을 것 같습니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                }, modifier = Modifier
이 부분은 한 줄로 처리할 수 있을 것 같아요.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                }, modifier = Modifier
여기도 한 줄로 수정해주실 수 있겠지요?

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                    containerColor = GoogleGray, contentColor = Color.Black
컨벤션 지켜주시면 가독성이 더 좋을 것 같습니다ㅎㅎ

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                            .size(18.dp)
여기도 같습니다. 또한, `modifier` 는 최상위에 있는 편이 좋아 보입니다..!

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                        text = "구글로 로그인",
해당 부분도 `strings.xml` 을 통해 선언되면 좋겠습니다.

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +}
최상위 수준에 `public` 으로 메서드를 선언한 이유가 있으실까요? 
가시성 제한자 잘 사용해주시고, 무엇보다 `ViewModel` 에서 이벤트로 처리해주면 될 부분으로 보입니다!

2023-11-20 08:29 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +}
추가로, `AuthResultContract` 클래스의 경우 외부로 빼는 편이 낫지 않을까 싶습니다. 이 부분은 딱히 수정하지 않으셔도 좋고요.

2023-11-20 08:30 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +}
주석도 가능하면 제거해주시는 쪽으로 생각해주시죠ㅎㅎ 주석이 필요 없는 부분이라 사료됩니다.

2023-11-20 09:23 UTC, upsk1 commented on client/presentation/build.gradle.kts
> +    implementation ("com.google.android.gms:play-services-auth:20.5.0")
수정했습니다 !!

2023-11-20 09:42 UTC, upsk1 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +    val signInRequestCode = 1
수정 完

2023-11-20 09:48 UTC, junjange approved these changes
기회가 되면 카카오랑 구글 로그인 부분을 모듈로 빼도 좋을 것 같아요!!

2023-11-20 09:59 UTC, upsk1 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                }, modifier = Modifier
onClick = { handleKakaoLogin(context) } 이렇게 말씀하시는 걸까요 ?!

2023-11-21 10:57 UTC, jangjh123 approved these changes
LGTM👍

2023-11-21 11:31 UTC, junjange approved these changes
고생하셨씁니다~~

2023-11-21 14:47 UTC, jangjh123 requested changes

2023-11-21 14:47 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                //TODO network error
👍

2023-11-21 14:47 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                                kakaoSignInClient.loginWithKakaoAccount(context, callback = { _, _ -> })
`named argument` 를 일관적으로 사용해주시면 좋을 것 같아요!

2023-11-21 14:47 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                        kakaoSignInClient.loginWithKakaoAccount(context, callback = { token, error ->
여기도요ㅎㅎ

2023-11-21 14:47 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                ), shape = RoundedCornerShape(10.dp)
줄바꿈 필요할 것 같습니다ㅎㅎ

2023-11-21 14:47 UTC, jangjh123 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                },
여기는 한 줄로 처리할 수 있을 것 같습니다ㅎㅎ

2023-11-21 14:50 UTC, upsk1 commented on client/presentation/src/main/java/com/everyone/movemove_android/ui/login/LoginScreen.kt
> +                //TODO network error
ㅎ

2023-11-21 14:57 UTC, jangjh123 approved these changes

2023-11-21 14:57 UTC, upsk1 commented
꼼꼼히 봐주셔서 너무 감사합니다..!

2023-11-21 14:57 UTC, merged